### PR TITLE
vsm rpm scripting from git tags

### PR DESCRIPTION
**Pull request by nichenke**
We have a combo of changes here by necessity - our build infrastructure can't handle old style builds with templated .spec, so we need both at once. 

First, we add upstream clean rules for make dist that includes the .tar and templates in the .spec. 

For our VSM build integration, we can now nuke the old pkg-linux makefile and now use a toplevel make rule that is much simpler. We are updating the mock_rpmbuild script to the latest from VSM, which allows us to have a consistent build environment.

### CODE REVIEW

**Comment by nichenke** [comment]
retest this please

**Comment by nichenke** [comment]
retest this please

**Comment by heemstra** [comment]
Looks OK to me... largely because it's pretty matchy matchy with the recent vsm changes.  

@benmcclelland ?

**Comment by benmcclelland** [comment]
looks good, merging

**Pull request merged**
